<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ContainersIdArchiveGetResponse400
{
    /**
     * The error message. Either "must specify path parameter".
     *
     * @var string
     */
    protected $message;

    /**
     * The error message. Either "must specify path parameter".
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * The error message. Either "must specify path parameter".
     */
    public function setMessage(?string $message): self
    {
        $this->message = $message;

        return $this;
    }
}
