<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ContainersIdTopGetResponse200
{
    /**
     * The ps column titles.
     *
     * @var string[]
     */
    protected $titles;
    /**
     * Each process running in the container, where each is process.
     *
     * @var string[][]
     */
    protected $processes;

    /**
     * The ps column titles.
     *
     * @return string[]|null
     */
    public function getTitles(): ?array
    {
        return $this->titles;
    }

    /**
     * The ps column titles.
     *
     * @param string[]|null $titles
     */
    public function setTitles(?array $titles): self
    {
        $this->titles = $titles;

        return $this;
    }

    /**
     * Each process running in the container, where each is process.
     *
     * @return string[][]|null
     */
    public function getProcesses(): ?array
    {
        return $this->processes;
    }

    /**
     * Each process running in the container, where each is process.
     *
     * @param string[][]|null $processes
     */
    public function setProcesses(?array $processes): self
    {
        $this->processes = $processes;

        return $this;
    }
}
