<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class EndpointSpec
{
    /**
     * The mode of resolution to use for internal load balancing between tasks.
     *
     * @var string
     */
    protected $mode = 'vip';
    /**
     * List of exposed ports that this service is accessible on from the.
     *
     * @var EndpointPortConfig[]
     */
    protected $ports;

    /**
     * The mode of resolution to use for internal load balancing between tasks.
     */
    public function getMode(): ?string
    {
        return $this->mode;
    }

    /**
     * The mode of resolution to use for internal load balancing between tasks.
     */
    public function setMode(?string $mode): self
    {
        $this->mode = $mode;

        return $this;
    }

    /**
     * List of exposed ports that this service is accessible on from the.
     *
     * @return EndpointPortConfig[]|null
     */
    public function getPorts(): ?array
    {
        return $this->ports;
    }

    /**
     * List of exposed ports that this service is accessible on from the.
     *
     * @param EndpointPortConfig[]|null $ports
     */
    public function setPorts(?array $ports): self
    {
        $this->ports = $ports;

        return $this;
    }
}
