<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ExecIdJsonGetResponse200
{
    /**
     * @var bool
     */
    protected $canRemove;
    /**
     * @var string
     */
    protected $detachKeys;
    /**
     * @var string
     */
    protected $iD;
    /**
     * @var bool
     */
    protected $running;
    /**
     * @var int
     */
    protected $exitCode;
    /**
     * @var ProcessConfig
     */
    protected $processConfig;
    /**
     * @var bool
     */
    protected $openStdin;
    /**
     * @var bool
     */
    protected $openStderr;
    /**
     * @var bool
     */
    protected $openStdout;
    /**
     * @var string
     */
    protected $containerID;
    /**
     * The system process ID for the exec process.
     *
     * @var int
     */
    protected $pid;

    public function getCanRemove(): ?bool
    {
        return $this->canRemove;
    }

    public function setCanRemove(?bool $canRemove): self
    {
        $this->canRemove = $canRemove;

        return $this;
    }

    public function getDetachKeys(): ?string
    {
        return $this->detachKeys;
    }

    public function setDetachKeys(?string $detachKeys): self
    {
        $this->detachKeys = $detachKeys;

        return $this;
    }

    public function getID(): ?string
    {
        return $this->iD;
    }

    public function setID(?string $iD): self
    {
        $this->iD = $iD;

        return $this;
    }

    public function getRunning(): ?bool
    {
        return $this->running;
    }

    public function setRunning(?bool $running): self
    {
        $this->running = $running;

        return $this;
    }

    public function getExitCode(): ?int
    {
        return $this->exitCode;
    }

    public function setExitCode(?int $exitCode): self
    {
        $this->exitCode = $exitCode;

        return $this;
    }

    public function getProcessConfig(): ?ProcessConfig
    {
        return $this->processConfig;
    }

    public function setProcessConfig(?ProcessConfig $processConfig): self
    {
        $this->processConfig = $processConfig;

        return $this;
    }

    public function getOpenStdin(): ?bool
    {
        return $this->openStdin;
    }

    public function setOpenStdin(?bool $openStdin): self
    {
        $this->openStdin = $openStdin;

        return $this;
    }

    public function getOpenStderr(): ?bool
    {
        return $this->openStderr;
    }

    public function setOpenStderr(?bool $openStderr): self
    {
        $this->openStderr = $openStderr;

        return $this;
    }

    public function getOpenStdout(): ?bool
    {
        return $this->openStdout;
    }

    public function setOpenStdout(?bool $openStdout): self
    {
        $this->openStdout = $openStdout;

        return $this;
    }

    public function getContainerID(): ?string
    {
        return $this->containerID;
    }

    public function setContainerID(?string $containerID): self
    {
        $this->containerID = $containerID;

        return $this;
    }

    /**
     * The system process ID for the exec process.
     */
    public function getPid(): ?int
    {
        return $this->pid;
    }

    /**
     * The system process ID for the exec process.
     */
    public function setPid(?int $pid): self
    {
        $this->pid = $pid;

        return $this;
    }
}
