<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class HostConfig
{
    /**
     * An integer value representing this container's relative CPU weight versus other containers.
     *
     * @var int
     */
    protected $cpuShares;
    /**
     * Memory limit in bytes.
     *
     * @var int
     */
    protected $memory = 0;
    /**
     * Path to `cgroups` under which the container's `cgroup` is created. If the path is not absolute, the path is considered to be relative to the `cgroups` path of the init process. Cgroups are created if they do not already exist.
     *
     * @var string
     */
    protected $cgroupParent;
    /**
     * Block IO weight (relative weight).
     *
     * @var int
     */
    protected $blkioWeight;
    /**
     * Block IO weight (relative device weight) in the form:.
     *
     * @var ResourcesBlkioWeightDeviceItem[]
     */
    protected $blkioWeightDevice;
    /**
     * Limit read rate (bytes per second) from a device, in the form:.
     *
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceReadBps;
    /**
     * Limit write rate (bytes per second) to a device, in the form:.
     *
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceWriteBps;
    /**
     * Limit read rate (IO per second) from a device, in the form:.
     *
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceReadIOps;
    /**
     * Limit write rate (IO per second) to a device, in the form:.
     *
     * @var ThrottleDevice[]
     */
    protected $blkioDeviceWriteIOps;
    /**
     * The length of a CPU period in microseconds.
     *
     * @var int
     */
    protected $cpuPeriod;
    /**
     * Microseconds of CPU time that the container can get in a CPU period.
     *
     * @var int
     */
    protected $cpuQuota;
    /**
     * The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     *
     * @var int
     */
    protected $cpuRealtimePeriod;
    /**
     * The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     *
     * @var int
     */
    protected $cpuRealtimeRuntime;
    /**
     * CPUs in which to allow execution (e.g., `0-3`, `0,1`).
     *
     * @var string
     */
    protected $cpusetCpus;
    /**
     * Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
     *
     * @var string
     */
    protected $cpusetMems;
    /**
     * A list of devices to add to the container.
     *
     * @var DeviceMapping[]
     */
    protected $devices;
    /**
     * a list of cgroup rules to apply to the container.
     *
     * @var string[]
     */
    protected $deviceCgroupRules;
    /**
     * A list of requests for devices to be sent to device drivers.
     *
     * @var DeviceRequest[]
     */
    protected $deviceRequests;
    /**
     * Kernel memory limit in bytes.
     *
     * @var int
     */
    protected $kernelMemory;
    /**
     * Hard limit for kernel TCP buffer memory (in bytes).
     *
     * @var int
     */
    protected $kernelMemoryTCP;
    /**
     * Memory soft limit in bytes.
     *
     * @var int
     */
    protected $memoryReservation;
    /**
     * Total memory limit (memory + swap). Set as `-1` to enable unlimited swap.
     *
     * @var int
     */
    protected $memorySwap;
    /**
     * Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.
     *
     * @var int
     */
    protected $memorySwappiness;
    /**
     * CPU quota in units of 10<sup>-9</sup> CPUs.
     *
     * @var int
     */
    protected $nanoCPUs;
    /**
     * Disable OOM Killer for the container.
     *
     * @var bool
     */
    protected $oomKillDisable;
    /**
     * Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.
     *
     * @var bool
     */
    protected $init;
    /**
     * Tune a container's PIDs limit. Set `0` or `-1` for unlimited, or `null` to not change.
     *
     * @var int
     */
    protected $pidsLimit;
    /**
     * A list of resource limits to set in the container. For example:.
     *
     * @var ResourcesUlimitsItem[]
     */
    protected $ulimits;
    /**
     * The number of usable CPUs (Windows only).
     *
     * @var int
     */
    protected $cpuCount;
    /**
     * The usable percentage of the available CPUs (Windows only).
     *
     * @var int
     */
    protected $cpuPercent;
    /**
     * Maximum IOps for the container system drive (Windows only).
     *
     * @var int
     */
    protected $iOMaximumIOps;
    /**
     * Maximum IO in bytes per second for the container system drive.
     *
     * @var int
     */
    protected $iOMaximumBandwidth;
    /**
     * A list of volume bindings for this container. Each volume binding.
     *
     * @var string[]
     */
    protected $binds;
    /**
     * Path to a file where the container ID is written.
     *
     * @var string
     */
    protected $containerIDFile;
    /**
     * The logging configuration for this container.
     *
     * @var HostConfigLogConfig
     */
    protected $logConfig;
    /**
     * Network mode to use for this container. Supported standard values.
     *
     * @var string
     */
    protected $networkMode;
    /**
     * PortMap describes the mapping of container ports to host ports, using the.
     *
     * @var PortBinding[][]
     */
    protected $portBindings;
    /**
     * The behavior to apply when the container exits. The default is not to restart.
     *
     * @var RestartPolicy
     */
    protected $restartPolicy;
    /**
     * Automatically remove the container when the container's process.
     *
     * @var bool
     */
    protected $autoRemove;
    /**
     * Driver that this container uses to mount volumes.
     *
     * @var string
     */
    protected $volumeDriver;
    /**
     * A list of volumes to inherit from another container, specified in.
     *
     * @var string[]
     */
    protected $volumesFrom;
    /**
     * Specification for mounts to be added to the container.
     *
     * @var Mount[]
     */
    protected $mounts;
    /**
     * A list of kernel capabilities to be available for container (this.
     *
     * @var string[]
     */
    protected $capabilities;
    /**
     * A list of kernel capabilities to add to the container. Conflicts.
     *
     * @var string[]
     */
    protected $capAdd;
    /**
     * A list of kernel capabilities to drop from the container. Conflicts.
     *
     * @var string[]
     */
    protected $capDrop;
    /**
     * A list of DNS servers for the container to use.
     *
     * @var string[]
     */
    protected $dns;
    /**
     * A list of DNS options.
     *
     * @var string[]
     */
    protected $dnsOptions;
    /**
     * A list of DNS search domains.
     *
     * @var string[]
     */
    protected $dnsSearch;
    /**
     * A list of hostnames/IP mappings to add to the container's `/etc/hosts`.
     *
     * @var string[]
     */
    protected $extraHosts;
    /**
     * A list of additional groups that the container process will run as.
     *
     * @var string[]
     */
    protected $groupAdd;
    /**
     * IPC sharing mode for the container. Possible values are:.
     *
     * @var string
     */
    protected $ipcMode;
    /**
     * Cgroup to use for the container.
     *
     * @var string
     */
    protected $cgroup;
    /**
     * A list of links for the container in the form `container_name:alias`.
     *
     * @var string[]
     */
    protected $links;
    /**
     * An integer value containing the score given to the container in.
     *
     * @var int
     */
    protected $oomScoreAdj;
    /**
     * Set the PID (Process) Namespace mode for the container. It can be.
     *
     * @var string
     */
    protected $pidMode;
    /**
     * Gives the container full access to the host.
     *
     * @var bool
     */
    protected $privileged;
    /**
     * Allocates an ephemeral host port for all of a container's.
     *
     * @var bool
     */
    protected $publishAllPorts;
    /**
     * Mount the container's root filesystem as read only.
     *
     * @var bool
     */
    protected $readonlyRootfs;
    /**
     * A list of string values to customize labels for MLS systems, such as SELinux.
     *
     * @var string[]
     */
    protected $securityOpt;
    /**
     * Storage driver options for this container, in the form `{"size": "120G"}`.
     *
     * @var string[]
     */
    protected $storageOpt;
    /**
     * A map of container directories which should be replaced by tmpfs.
     *
     * @var string[]
     */
    protected $tmpfs;
    /**
     * UTS namespace to use for the container.
     *
     * @var string
     */
    protected $uTSMode;
    /**
     * Sets the usernamespace mode for the container when usernamespace.
     *
     * @var string
     */
    protected $usernsMode;
    /**
     * Size of `/dev/shm` in bytes. If omitted, the system uses 64MB.
     *
     * @var int
     */
    protected $shmSize;
    /**
     * A list of kernel parameters (sysctls) to set in the container.
     *
     * @var string[]
     */
    protected $sysctls;
    /**
     * Runtime to use with this container.
     *
     * @var string
     */
    protected $runtime;
    /**
     * Initial console size, as an `[height, width]` array. (Windows only).
     *
     * @var int[]
     */
    protected $consoleSize;
    /**
     * Isolation technology of the container. (Windows only).
     *
     * @var string
     */
    protected $isolation;
    /**
     * The list of paths to be masked inside the container (this overrides.
     *
     * @var string[]
     */
    protected $maskedPaths;
    /**
     * The list of paths to be set as read-only inside the container.
     *
     * @var string[]
     */
    protected $readonlyPaths;

    /**
     * An integer value representing this container's relative CPU weight versus other containers.
     */
    public function getCpuShares(): ?int
    {
        return $this->cpuShares;
    }

    /**
     * An integer value representing this container's relative CPU weight versus other containers.
     */
    public function setCpuShares(?int $cpuShares): self
    {
        $this->cpuShares = $cpuShares;

        return $this;
    }

    /**
     * Memory limit in bytes.
     */
    public function getMemory(): ?int
    {
        return $this->memory;
    }

    /**
     * Memory limit in bytes.
     */
    public function setMemory(?int $memory): self
    {
        $this->memory = $memory;

        return $this;
    }

    /**
     * Path to `cgroups` under which the container's `cgroup` is created. If the path is not absolute, the path is considered to be relative to the `cgroups` path of the init process. Cgroups are created if they do not already exist.
     */
    public function getCgroupParent(): ?string
    {
        return $this->cgroupParent;
    }

    /**
     * Path to `cgroups` under which the container's `cgroup` is created. If the path is not absolute, the path is considered to be relative to the `cgroups` path of the init process. Cgroups are created if they do not already exist.
     */
    public function setCgroupParent(?string $cgroupParent): self
    {
        $this->cgroupParent = $cgroupParent;

        return $this;
    }

    /**
     * Block IO weight (relative weight).
     */
    public function getBlkioWeight(): ?int
    {
        return $this->blkioWeight;
    }

    /**
     * Block IO weight (relative weight).
     */
    public function setBlkioWeight(?int $blkioWeight): self
    {
        $this->blkioWeight = $blkioWeight;

        return $this;
    }

    /**
     * Block IO weight (relative device weight) in the form:.
     *
     * @return ResourcesBlkioWeightDeviceItem[]|null
     */
    public function getBlkioWeightDevice(): ?array
    {
        return $this->blkioWeightDevice;
    }

    /**
     * Block IO weight (relative device weight) in the form:.
     *
     * @param ResourcesBlkioWeightDeviceItem[]|null $blkioWeightDevice
     */
    public function setBlkioWeightDevice(?array $blkioWeightDevice): self
    {
        $this->blkioWeightDevice = $blkioWeightDevice;

        return $this;
    }

    /**
     * Limit read rate (bytes per second) from a device, in the form:.
     *
     * @return ThrottleDevice[]|null
     */
    public function getBlkioDeviceReadBps(): ?array
    {
        return $this->blkioDeviceReadBps;
    }

    /**
     * Limit read rate (bytes per second) from a device, in the form:.
     *
     * @param ThrottleDevice[]|null $blkioDeviceReadBps
     */
    public function setBlkioDeviceReadBps(?array $blkioDeviceReadBps): self
    {
        $this->blkioDeviceReadBps = $blkioDeviceReadBps;

        return $this;
    }

    /**
     * Limit write rate (bytes per second) to a device, in the form:.
     *
     * @return ThrottleDevice[]|null
     */
    public function getBlkioDeviceWriteBps(): ?array
    {
        return $this->blkioDeviceWriteBps;
    }

    /**
     * Limit write rate (bytes per second) to a device, in the form:.
     *
     * @param ThrottleDevice[]|null $blkioDeviceWriteBps
     */
    public function setBlkioDeviceWriteBps(?array $blkioDeviceWriteBps): self
    {
        $this->blkioDeviceWriteBps = $blkioDeviceWriteBps;

        return $this;
    }

    /**
     * Limit read rate (IO per second) from a device, in the form:.
     *
     * @return ThrottleDevice[]|null
     */
    public function getBlkioDeviceReadIOps(): ?array
    {
        return $this->blkioDeviceReadIOps;
    }

    /**
     * Limit read rate (IO per second) from a device, in the form:.
     *
     * @param ThrottleDevice[]|null $blkioDeviceReadIOps
     */
    public function setBlkioDeviceReadIOps(?array $blkioDeviceReadIOps): self
    {
        $this->blkioDeviceReadIOps = $blkioDeviceReadIOps;

        return $this;
    }

    /**
     * Limit write rate (IO per second) to a device, in the form:.
     *
     * @return ThrottleDevice[]|null
     */
    public function getBlkioDeviceWriteIOps(): ?array
    {
        return $this->blkioDeviceWriteIOps;
    }

    /**
     * Limit write rate (IO per second) to a device, in the form:.
     *
     * @param ThrottleDevice[]|null $blkioDeviceWriteIOps
     */
    public function setBlkioDeviceWriteIOps(?array $blkioDeviceWriteIOps): self
    {
        $this->blkioDeviceWriteIOps = $blkioDeviceWriteIOps;

        return $this;
    }

    /**
     * The length of a CPU period in microseconds.
     */
    public function getCpuPeriod(): ?int
    {
        return $this->cpuPeriod;
    }

    /**
     * The length of a CPU period in microseconds.
     */
    public function setCpuPeriod(?int $cpuPeriod): self
    {
        $this->cpuPeriod = $cpuPeriod;

        return $this;
    }

    /**
     * Microseconds of CPU time that the container can get in a CPU period.
     */
    public function getCpuQuota(): ?int
    {
        return $this->cpuQuota;
    }

    /**
     * Microseconds of CPU time that the container can get in a CPU period.
     */
    public function setCpuQuota(?int $cpuQuota): self
    {
        $this->cpuQuota = $cpuQuota;

        return $this;
    }

    /**
     * The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    public function getCpuRealtimePeriod(): ?int
    {
        return $this->cpuRealtimePeriod;
    }

    /**
     * The length of a CPU real-time period in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    public function setCpuRealtimePeriod(?int $cpuRealtimePeriod): self
    {
        $this->cpuRealtimePeriod = $cpuRealtimePeriod;

        return $this;
    }

    /**
     * The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    public function getCpuRealtimeRuntime(): ?int
    {
        return $this->cpuRealtimeRuntime;
    }

    /**
     * The length of a CPU real-time runtime in microseconds. Set to 0 to allocate no time allocated to real-time tasks.
     */
    public function setCpuRealtimeRuntime(?int $cpuRealtimeRuntime): self
    {
        $this->cpuRealtimeRuntime = $cpuRealtimeRuntime;

        return $this;
    }

    /**
     * CPUs in which to allow execution (e.g., `0-3`, `0,1`).
     */
    public function getCpusetCpus(): ?string
    {
        return $this->cpusetCpus;
    }

    /**
     * CPUs in which to allow execution (e.g., `0-3`, `0,1`).
     */
    public function setCpusetCpus(?string $cpusetCpus): self
    {
        $this->cpusetCpus = $cpusetCpus;

        return $this;
    }

    /**
     * Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
     */
    public function getCpusetMems(): ?string
    {
        return $this->cpusetMems;
    }

    /**
     * Memory nodes (MEMs) in which to allow execution (0-3, 0,1). Only effective on NUMA systems.
     */
    public function setCpusetMems(?string $cpusetMems): self
    {
        $this->cpusetMems = $cpusetMems;

        return $this;
    }

    /**
     * A list of devices to add to the container.
     *
     * @return DeviceMapping[]|null
     */
    public function getDevices(): ?array
    {
        return $this->devices;
    }

    /**
     * A list of devices to add to the container.
     *
     * @param DeviceMapping[]|null $devices
     */
    public function setDevices(?array $devices): self
    {
        $this->devices = $devices;

        return $this;
    }

    /**
     * a list of cgroup rules to apply to the container.
     *
     * @return string[]|null
     */
    public function getDeviceCgroupRules(): ?array
    {
        return $this->deviceCgroupRules;
    }

    /**
     * a list of cgroup rules to apply to the container.
     *
     * @param string[]|null $deviceCgroupRules
     */
    public function setDeviceCgroupRules(?array $deviceCgroupRules): self
    {
        $this->deviceCgroupRules = $deviceCgroupRules;

        return $this;
    }

    /**
     * A list of requests for devices to be sent to device drivers.
     *
     * @return DeviceRequest[]|null
     */
    public function getDeviceRequests(): ?array
    {
        return $this->deviceRequests;
    }

    /**
     * A list of requests for devices to be sent to device drivers.
     *
     * @param DeviceRequest[]|null $deviceRequests
     */
    public function setDeviceRequests(?array $deviceRequests): self
    {
        $this->deviceRequests = $deviceRequests;

        return $this;
    }

    /**
     * Kernel memory limit in bytes.
     */
    public function getKernelMemory(): ?int
    {
        return $this->kernelMemory;
    }

    /**
     * Kernel memory limit in bytes.
     */
    public function setKernelMemory(?int $kernelMemory): self
    {
        $this->kernelMemory = $kernelMemory;

        return $this;
    }

    /**
     * Hard limit for kernel TCP buffer memory (in bytes).
     */
    public function getKernelMemoryTCP(): ?int
    {
        return $this->kernelMemoryTCP;
    }

    /**
     * Hard limit for kernel TCP buffer memory (in bytes).
     */
    public function setKernelMemoryTCP(?int $kernelMemoryTCP): self
    {
        $this->kernelMemoryTCP = $kernelMemoryTCP;

        return $this;
    }

    /**
     * Memory soft limit in bytes.
     */
    public function getMemoryReservation(): ?int
    {
        return $this->memoryReservation;
    }

    /**
     * Memory soft limit in bytes.
     */
    public function setMemoryReservation(?int $memoryReservation): self
    {
        $this->memoryReservation = $memoryReservation;

        return $this;
    }

    /**
     * Total memory limit (memory + swap). Set as `-1` to enable unlimited swap.
     */
    public function getMemorySwap(): ?int
    {
        return $this->memorySwap;
    }

    /**
     * Total memory limit (memory + swap). Set as `-1` to enable unlimited swap.
     */
    public function setMemorySwap(?int $memorySwap): self
    {
        $this->memorySwap = $memorySwap;

        return $this;
    }

    /**
     * Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.
     */
    public function getMemorySwappiness(): ?int
    {
        return $this->memorySwappiness;
    }

    /**
     * Tune a container's memory swappiness behavior. Accepts an integer between 0 and 100.
     */
    public function setMemorySwappiness(?int $memorySwappiness): self
    {
        $this->memorySwappiness = $memorySwappiness;

        return $this;
    }

    /**
     * CPU quota in units of 10<sup>-9</sup> CPUs.
     */
    public function getNanoCPUs(): ?int
    {
        return $this->nanoCPUs;
    }

    /**
     * CPU quota in units of 10<sup>-9</sup> CPUs.
     */
    public function setNanoCPUs(?int $nanoCPUs): self
    {
        $this->nanoCPUs = $nanoCPUs;

        return $this;
    }

    /**
     * Disable OOM Killer for the container.
     */
    public function getOomKillDisable(): ?bool
    {
        return $this->oomKillDisable;
    }

    /**
     * Disable OOM Killer for the container.
     */
    public function setOomKillDisable(?bool $oomKillDisable): self
    {
        $this->oomKillDisable = $oomKillDisable;

        return $this;
    }

    /**
     * Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.
     */
    public function getInit(): ?bool
    {
        return $this->init;
    }

    /**
     * Run an init inside the container that forwards signals and reaps processes. This field is omitted if empty, and the default (as configured on the daemon) is used.
     */
    public function setInit(?bool $init): self
    {
        $this->init = $init;

        return $this;
    }

    /**
     * Tune a container's PIDs limit. Set `0` or `-1` for unlimited, or `null` to not change.
     */
    public function getPidsLimit(): ?int
    {
        return $this->pidsLimit;
    }

    /**
     * Tune a container's PIDs limit. Set `0` or `-1` for unlimited, or `null` to not change.
     */
    public function setPidsLimit(?int $pidsLimit): self
    {
        $this->pidsLimit = $pidsLimit;

        return $this;
    }

    /**
     * A list of resource limits to set in the container. For example:.
     *
     * @return ResourcesUlimitsItem[]|null
     */
    public function getUlimits(): ?array
    {
        return $this->ulimits;
    }

    /**
     * A list of resource limits to set in the container. For example:.
     *
     * @param ResourcesUlimitsItem[]|null $ulimits
     */
    public function setUlimits(?array $ulimits): self
    {
        $this->ulimits = $ulimits;

        return $this;
    }

    /**
     * The number of usable CPUs (Windows only).
     */
    public function getCpuCount(): ?int
    {
        return $this->cpuCount;
    }

    /**
     * The number of usable CPUs (Windows only).
     */
    public function setCpuCount(?int $cpuCount): self
    {
        $this->cpuCount = $cpuCount;

        return $this;
    }

    /**
     * The usable percentage of the available CPUs (Windows only).
     */
    public function getCpuPercent(): ?int
    {
        return $this->cpuPercent;
    }

    /**
     * The usable percentage of the available CPUs (Windows only).
     */
    public function setCpuPercent(?int $cpuPercent): self
    {
        $this->cpuPercent = $cpuPercent;

        return $this;
    }

    /**
     * Maximum IOps for the container system drive (Windows only).
     */
    public function getIOMaximumIOps(): ?int
    {
        return $this->iOMaximumIOps;
    }

    /**
     * Maximum IOps for the container system drive (Windows only).
     */
    public function setIOMaximumIOps(?int $iOMaximumIOps): self
    {
        $this->iOMaximumIOps = $iOMaximumIOps;

        return $this;
    }

    /**
     * Maximum IO in bytes per second for the container system drive.
     */
    public function getIOMaximumBandwidth(): ?int
    {
        return $this->iOMaximumBandwidth;
    }

    /**
     * Maximum IO in bytes per second for the container system drive.
     */
    public function setIOMaximumBandwidth(?int $iOMaximumBandwidth): self
    {
        $this->iOMaximumBandwidth = $iOMaximumBandwidth;

        return $this;
    }

    /**
     * A list of volume bindings for this container. Each volume binding.
     *
     * @return string[]|null
     */
    public function getBinds(): ?array
    {
        return $this->binds;
    }

    /**
     * A list of volume bindings for this container. Each volume binding.
     *
     * @param string[]|null $binds
     */
    public function setBinds(?array $binds): self
    {
        $this->binds = $binds;

        return $this;
    }

    /**
     * Path to a file where the container ID is written.
     */
    public function getContainerIDFile(): ?string
    {
        return $this->containerIDFile;
    }

    /**
     * Path to a file where the container ID is written.
     */
    public function setContainerIDFile(?string $containerIDFile): self
    {
        $this->containerIDFile = $containerIDFile;

        return $this;
    }

    /**
     * The logging configuration for this container.
     */
    public function getLogConfig(): ?HostConfigLogConfig
    {
        return $this->logConfig;
    }

    /**
     * The logging configuration for this container.
     */
    public function setLogConfig(?HostConfigLogConfig $logConfig): self
    {
        $this->logConfig = $logConfig;

        return $this;
    }

    /**
     * Network mode to use for this container. Supported standard values.
     */
    public function getNetworkMode(): ?string
    {
        return $this->networkMode;
    }

    /**
     * Network mode to use for this container. Supported standard values.
     */
    public function setNetworkMode(?string $networkMode): self
    {
        $this->networkMode = $networkMode;

        return $this;
    }

    /**
     * PortMap describes the mapping of container ports to host ports, using the.
     *
     * @return PortBinding[][]|null
     */
    public function getPortBindings(): ?\ArrayObject
    {
        return $this->portBindings;
    }

    /**
     * PortMap describes the mapping of container ports to host ports, using the.
     *
     * @param PortBinding[][]|null $portBindings
     */
    public function setPortBindings(?\ArrayObject $portBindings): self
    {
        $this->portBindings = $portBindings;

        return $this;
    }

    /**
     * The behavior to apply when the container exits. The default is not to restart.
     */
    public function getRestartPolicy(): ?RestartPolicy
    {
        return $this->restartPolicy;
    }

    /**
     * The behavior to apply when the container exits. The default is not to restart.
     */
    public function setRestartPolicy(?RestartPolicy $restartPolicy): self
    {
        $this->restartPolicy = $restartPolicy;

        return $this;
    }

    /**
     * Automatically remove the container when the container's process.
     */
    public function getAutoRemove(): ?bool
    {
        return $this->autoRemove;
    }

    /**
     * Automatically remove the container when the container's process.
     */
    public function setAutoRemove(?bool $autoRemove): self
    {
        $this->autoRemove = $autoRemove;

        return $this;
    }

    /**
     * Driver that this container uses to mount volumes.
     */
    public function getVolumeDriver(): ?string
    {
        return $this->volumeDriver;
    }

    /**
     * Driver that this container uses to mount volumes.
     */
    public function setVolumeDriver(?string $volumeDriver): self
    {
        $this->volumeDriver = $volumeDriver;

        return $this;
    }

    /**
     * A list of volumes to inherit from another container, specified in.
     *
     * @return string[]|null
     */
    public function getVolumesFrom(): ?array
    {
        return $this->volumesFrom;
    }

    /**
     * A list of volumes to inherit from another container, specified in.
     *
     * @param string[]|null $volumesFrom
     */
    public function setVolumesFrom(?array $volumesFrom): self
    {
        $this->volumesFrom = $volumesFrom;

        return $this;
    }

    /**
     * Specification for mounts to be added to the container.
     *
     * @return Mount[]|null
     */
    public function getMounts(): ?array
    {
        return $this->mounts;
    }

    /**
     * Specification for mounts to be added to the container.
     *
     * @param Mount[]|null $mounts
     */
    public function setMounts(?array $mounts): self
    {
        $this->mounts = $mounts;

        return $this;
    }

    /**
     * A list of kernel capabilities to be available for container (this.
     *
     * @return string[]|null
     */
    public function getCapabilities(): ?array
    {
        return $this->capabilities;
    }

    /**
     * A list of kernel capabilities to be available for container (this.
     *
     * @param string[]|null $capabilities
     */
    public function setCapabilities(?array $capabilities): self
    {
        $this->capabilities = $capabilities;

        return $this;
    }

    /**
     * A list of kernel capabilities to add to the container. Conflicts.
     *
     * @return string[]|null
     */
    public function getCapAdd(): ?array
    {
        return $this->capAdd;
    }

    /**
     * A list of kernel capabilities to add to the container. Conflicts.
     *
     * @param string[]|null $capAdd
     */
    public function setCapAdd(?array $capAdd): self
    {
        $this->capAdd = $capAdd;

        return $this;
    }

    /**
     * A list of kernel capabilities to drop from the container. Conflicts.
     *
     * @return string[]|null
     */
    public function getCapDrop(): ?array
    {
        return $this->capDrop;
    }

    /**
     * A list of kernel capabilities to drop from the container. Conflicts.
     *
     * @param string[]|null $capDrop
     */
    public function setCapDrop(?array $capDrop): self
    {
        $this->capDrop = $capDrop;

        return $this;
    }

    /**
     * A list of DNS servers for the container to use.
     *
     * @return string[]|null
     */
    public function getDns(): ?array
    {
        return $this->dns;
    }

    /**
     * A list of DNS servers for the container to use.
     *
     * @param string[]|null $dns
     */
    public function setDns(?array $dns): self
    {
        $this->dns = $dns;

        return $this;
    }

    /**
     * A list of DNS options.
     *
     * @return string[]|null
     */
    public function getDnsOptions(): ?array
    {
        return $this->dnsOptions;
    }

    /**
     * A list of DNS options.
     *
     * @param string[]|null $dnsOptions
     */
    public function setDnsOptions(?array $dnsOptions): self
    {
        $this->dnsOptions = $dnsOptions;

        return $this;
    }

    /**
     * A list of DNS search domains.
     *
     * @return string[]|null
     */
    public function getDnsSearch(): ?array
    {
        return $this->dnsSearch;
    }

    /**
     * A list of DNS search domains.
     *
     * @param string[]|null $dnsSearch
     */
    public function setDnsSearch(?array $dnsSearch): self
    {
        $this->dnsSearch = $dnsSearch;

        return $this;
    }

    /**
     * A list of hostnames/IP mappings to add to the container's `/etc/hosts`.
     *
     * @return string[]|null
     */
    public function getExtraHosts(): ?array
    {
        return $this->extraHosts;
    }

    /**
     * A list of hostnames/IP mappings to add to the container's `/etc/hosts`.
     *
     * @param string[]|null $extraHosts
     */
    public function setExtraHosts(?array $extraHosts): self
    {
        $this->extraHosts = $extraHosts;

        return $this;
    }

    /**
     * A list of additional groups that the container process will run as.
     *
     * @return string[]|null
     */
    public function getGroupAdd(): ?array
    {
        return $this->groupAdd;
    }

    /**
     * A list of additional groups that the container process will run as.
     *
     * @param string[]|null $groupAdd
     */
    public function setGroupAdd(?array $groupAdd): self
    {
        $this->groupAdd = $groupAdd;

        return $this;
    }

    /**
     * IPC sharing mode for the container. Possible values are:.
     */
    public function getIpcMode(): ?string
    {
        return $this->ipcMode;
    }

    /**
     * IPC sharing mode for the container. Possible values are:.
     */
    public function setIpcMode(?string $ipcMode): self
    {
        $this->ipcMode = $ipcMode;

        return $this;
    }

    /**
     * Cgroup to use for the container.
     */
    public function getCgroup(): ?string
    {
        return $this->cgroup;
    }

    /**
     * Cgroup to use for the container.
     */
    public function setCgroup(?string $cgroup): self
    {
        $this->cgroup = $cgroup;

        return $this;
    }

    /**
     * A list of links for the container in the form `container_name:alias`.
     *
     * @return string[]|null
     */
    public function getLinks(): ?array
    {
        return $this->links;
    }

    /**
     * A list of links for the container in the form `container_name:alias`.
     *
     * @param string[]|null $links
     */
    public function setLinks(?array $links): self
    {
        $this->links = $links;

        return $this;
    }

    /**
     * An integer value containing the score given to the container in.
     */
    public function getOomScoreAdj(): ?int
    {
        return $this->oomScoreAdj;
    }

    /**
     * An integer value containing the score given to the container in.
     */
    public function setOomScoreAdj(?int $oomScoreAdj): self
    {
        $this->oomScoreAdj = $oomScoreAdj;

        return $this;
    }

    /**
     * Set the PID (Process) Namespace mode for the container. It can be.
     */
    public function getPidMode(): ?string
    {
        return $this->pidMode;
    }

    /**
     * Set the PID (Process) Namespace mode for the container. It can be.
     */
    public function setPidMode(?string $pidMode): self
    {
        $this->pidMode = $pidMode;

        return $this;
    }

    /**
     * Gives the container full access to the host.
     */
    public function getPrivileged(): ?bool
    {
        return $this->privileged;
    }

    /**
     * Gives the container full access to the host.
     */
    public function setPrivileged(?bool $privileged): self
    {
        $this->privileged = $privileged;

        return $this;
    }

    /**
     * Allocates an ephemeral host port for all of a container's.
     */
    public function getPublishAllPorts(): ?bool
    {
        return $this->publishAllPorts;
    }

    /**
     * Allocates an ephemeral host port for all of a container's.
     */
    public function setPublishAllPorts(?bool $publishAllPorts): self
    {
        $this->publishAllPorts = $publishAllPorts;

        return $this;
    }

    /**
     * Mount the container's root filesystem as read only.
     */
    public function getReadonlyRootfs(): ?bool
    {
        return $this->readonlyRootfs;
    }

    /**
     * Mount the container's root filesystem as read only.
     */
    public function setReadonlyRootfs(?bool $readonlyRootfs): self
    {
        $this->readonlyRootfs = $readonlyRootfs;

        return $this;
    }

    /**
     * A list of string values to customize labels for MLS systems, such as SELinux.
     *
     * @return string[]|null
     */
    public function getSecurityOpt(): ?array
    {
        return $this->securityOpt;
    }

    /**
     * A list of string values to customize labels for MLS systems, such as SELinux.
     *
     * @param string[]|null $securityOpt
     */
    public function setSecurityOpt(?array $securityOpt): self
    {
        $this->securityOpt = $securityOpt;

        return $this;
    }

    /**
     * Storage driver options for this container, in the form `{"size": "120G"}`.
     *
     * @return string[]|null
     */
    public function getStorageOpt(): ?\ArrayObject
    {
        return $this->storageOpt;
    }

    /**
     * Storage driver options for this container, in the form `{"size": "120G"}`.
     *
     * @param string[]|null $storageOpt
     */
    public function setStorageOpt(?\ArrayObject $storageOpt): self
    {
        $this->storageOpt = $storageOpt;

        return $this;
    }

    /**
     * A map of container directories which should be replaced by tmpfs.
     *
     * @return string[]|null
     */
    public function getTmpfs(): ?\ArrayObject
    {
        return $this->tmpfs;
    }

    /**
     * A map of container directories which should be replaced by tmpfs.
     *
     * @param string[]|null $tmpfs
     */
    public function setTmpfs(?\ArrayObject $tmpfs): self
    {
        $this->tmpfs = $tmpfs;

        return $this;
    }

    /**
     * UTS namespace to use for the container.
     */
    public function getUTSMode(): ?string
    {
        return $this->uTSMode;
    }

    /**
     * UTS namespace to use for the container.
     */
    public function setUTSMode(?string $uTSMode): self
    {
        $this->uTSMode = $uTSMode;

        return $this;
    }

    /**
     * Sets the usernamespace mode for the container when usernamespace.
     */
    public function getUsernsMode(): ?string
    {
        return $this->usernsMode;
    }

    /**
     * Sets the usernamespace mode for the container when usernamespace.
     */
    public function setUsernsMode(?string $usernsMode): self
    {
        $this->usernsMode = $usernsMode;

        return $this;
    }

    /**
     * Size of `/dev/shm` in bytes. If omitted, the system uses 64MB.
     */
    public function getShmSize(): ?int
    {
        return $this->shmSize;
    }

    /**
     * Size of `/dev/shm` in bytes. If omitted, the system uses 64MB.
     */
    public function setShmSize(?int $shmSize): self
    {
        $this->shmSize = $shmSize;

        return $this;
    }

    /**
     * A list of kernel parameters (sysctls) to set in the container.
     *
     * @return string[]|null
     */
    public function getSysctls(): ?\ArrayObject
    {
        return $this->sysctls;
    }

    /**
     * A list of kernel parameters (sysctls) to set in the container.
     *
     * @param string[]|null $sysctls
     */
    public function setSysctls(?\ArrayObject $sysctls): self
    {
        $this->sysctls = $sysctls;

        return $this;
    }

    /**
     * Runtime to use with this container.
     */
    public function getRuntime(): ?string
    {
        return $this->runtime;
    }

    /**
     * Runtime to use with this container.
     */
    public function setRuntime(?string $runtime): self
    {
        $this->runtime = $runtime;

        return $this;
    }

    /**
     * Initial console size, as an `[height, width]` array. (Windows only).
     *
     * @return int[]|null
     */
    public function getConsoleSize(): ?array
    {
        return $this->consoleSize;
    }

    /**
     * Initial console size, as an `[height, width]` array. (Windows only).
     *
     * @param int[]|null $consoleSize
     */
    public function setConsoleSize(?array $consoleSize): self
    {
        $this->consoleSize = $consoleSize;

        return $this;
    }

    /**
     * Isolation technology of the container. (Windows only).
     */
    public function getIsolation(): ?string
    {
        return $this->isolation;
    }

    /**
     * Isolation technology of the container. (Windows only).
     */
    public function setIsolation(?string $isolation): self
    {
        $this->isolation = $isolation;

        return $this;
    }

    /**
     * The list of paths to be masked inside the container (this overrides.
     *
     * @return string[]|null
     */
    public function getMaskedPaths(): ?array
    {
        return $this->maskedPaths;
    }

    /**
     * The list of paths to be masked inside the container (this overrides.
     *
     * @param string[]|null $maskedPaths
     */
    public function setMaskedPaths(?array $maskedPaths): self
    {
        $this->maskedPaths = $maskedPaths;

        return $this;
    }

    /**
     * The list of paths to be set as read-only inside the container.
     *
     * @return string[]|null
     */
    public function getReadonlyPaths(): ?array
    {
        return $this->readonlyPaths;
    }

    /**
     * The list of paths to be set as read-only inside the container.
     *
     * @param string[]|null $readonlyPaths
     */
    public function setReadonlyPaths(?array $readonlyPaths): self
    {
        $this->readonlyPaths = $readonlyPaths;

        return $this;
    }
}
