<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class IndexInfo
{
    /**
     * Name of the registry, such as "docker.io".
     *
     * @var string
     */
    protected $name;
    /**
     * List of mirrors, expressed as URIs.
     *
     * @var string[]
     */
    protected $mirrors;
    /**
     * Indicates if the registry is part of the list of insecure.

    > **Warning**: Insecure registries can be useful when running a local
     *
     * @var bool
     */
    protected $secure;
    /**
     * Indicates whether this is an official registry (i.e., Docker Hub / docker.io).
     *
     * @var bool
     */
    protected $official;

    /**
     * Name of the registry, such as "docker.io".
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the registry, such as "docker.io".
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * List of mirrors, expressed as URIs.
     *
     * @return string[]|null
     */
    public function getMirrors(): ?array
    {
        return $this->mirrors;
    }

    /**
     * List of mirrors, expressed as URIs.
     *
     * @param string[]|null $mirrors
     */
    public function setMirrors(?array $mirrors): self
    {
        $this->mirrors = $mirrors;

        return $this;
    }

    /**
     * Indicates if the registry is part of the list of insecure.

    > **Warning**: Insecure registries can be useful when running a local
    > registry. However, because its use creates security vulnerabilities
    > it should ONLY be enabled for testing purposes. For increased
    > security, users should add their CA to their system's list of
    > trusted CAs instead of enabling this option.
     */
    public function getSecure(): ?bool
    {
        return $this->secure;
    }

    /**
     * Indicates if the registry is part of the list of insecure.

    > **Warning**: Insecure registries can be useful when running a local
    > registry. However, because its use creates security vulnerabilities
    > it should ONLY be enabled for testing purposes. For increased
    > security, users should add their CA to their system's list of
    > trusted CAs instead of enabling this option.
     */
    public function setSecure(?bool $secure): self
    {
        $this->secure = $secure;

        return $this;
    }

    /**
     * Indicates whether this is an official registry (i.e., Docker Hub / docker.io).
     */
    public function getOfficial(): ?bool
    {
        return $this->official;
    }

    /**
     * Indicates whether this is an official registry (i.e., Docker Hub / docker.io).
     */
    public function setOfficial(?bool $official): self
    {
        $this->official = $official;

        return $this;
    }
}
