<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class IPAM
{
    /**
     * Name of the IPAM driver to use.
     *
     * @var string
     */
    protected $driver = 'default';
    /**
     * List of IPAM configuration options, specified as a map:.
     *
     * @var string[][]
     */
    protected $config;
    /**
     * Driver-specific options, specified as a map.
     *
     * @var string[]
     */
    protected $options;

    /**
     * Name of the IPAM driver to use.
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * Name of the IPAM driver to use.
     */
    public function setDriver(?string $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * List of IPAM configuration options, specified as a map:.
     *
     * @return string[][]|null
     */
    public function getConfig(): ?array
    {
        return $this->config;
    }

    /**
     * List of IPAM configuration options, specified as a map:.
     *
     * @param string[][]|null $config
     */
    public function setConfig(?array $config): self
    {
        $this->config = $config;

        return $this;
    }

    /**
     * Driver-specific options, specified as a map.
     *
     * @return string[]|null
     */
    public function getOptions(): ?\ArrayObject
    {
        return $this->options;
    }

    /**
     * Driver-specific options, specified as a map.
     *
     * @param string[]|null $options
     */
    public function setOptions(?\ArrayObject $options): self
    {
        $this->options = $options;

        return $this;
    }
}
