<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class NetworkAttachmentConfig
{
    /**
     * The target network for attachment. Must be a network name or ID.
     *
     * @var string
     */
    protected $target;
    /**
     * Discoverable alternate names for the service on this network.
     *
     * @var string[]
     */
    protected $aliases;
    /**
     * Driver attachment options for the network target.
     *
     * @var string[]
     */
    protected $driverOpts;

    /**
     * The target network for attachment. Must be a network name or ID.
     */
    public function getTarget(): ?string
    {
        return $this->target;
    }

    /**
     * The target network for attachment. Must be a network name or ID.
     */
    public function setTarget(?string $target): self
    {
        $this->target = $target;

        return $this;
    }

    /**
     * Discoverable alternate names for the service on this network.
     *
     * @return string[]|null
     */
    public function getAliases(): ?array
    {
        return $this->aliases;
    }

    /**
     * Discoverable alternate names for the service on this network.
     *
     * @param string[]|null $aliases
     */
    public function setAliases(?array $aliases): self
    {
        $this->aliases = $aliases;

        return $this;
    }

    /**
     * Driver attachment options for the network target.
     *
     * @return string[]|null
     */
    public function getDriverOpts(): ?\ArrayObject
    {
        return $this->driverOpts;
    }

    /**
     * Driver attachment options for the network target.
     *
     * @param string[]|null $driverOpts
     */
    public function setDriverOpts(?\ArrayObject $driverOpts): self
    {
        $this->driverOpts = $driverOpts;

        return $this;
    }
}
