<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class NetworksPrunePostResponse200
{
    /**
     * Networks that were deleted.
     *
     * @var string[]
     */
    protected $networksDeleted;

    /**
     * Networks that were deleted.
     *
     * @return string[]|null
     */
    public function getNetworksDeleted(): ?array
    {
        return $this->networksDeleted;
    }

    /**
     * Networks that were deleted.
     *
     * @param string[]|null $networksDeleted
     */
    public function setNetworksDeleted(?array $networksDeleted): self
    {
        $this->networksDeleted = $networksDeleted;

        return $this;
    }
}
