<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class NodeSpec
{
    /**
     * Name for the node.
     *
     * @var string
     */
    protected $name;
    /**
     * User-defined key/value metadata.
     *
     * @var string[]
     */
    protected $labels;
    /**
     * Role of the node.
     *
     * @var string
     */
    protected $role;
    /**
     * Availability of the node.
     *
     * @var string
     */
    protected $availability;

    /**
     * Name for the node.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name for the node.
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * User-defined key/value metadata.
     *
     * @return string[]|null
     */
    public function getLabels(): ?\ArrayObject
    {
        return $this->labels;
    }

    /**
     * User-defined key/value metadata.
     *
     * @param string[]|null $labels
     */
    public function setLabels(?\ArrayObject $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * Role of the node.
     */
    public function getRole(): ?string
    {
        return $this->role;
    }

    /**
     * Role of the node.
     */
    public function setRole(?string $role): self
    {
        $this->role = $role;

        return $this;
    }

    /**
     * Availability of the node.
     */
    public function getAvailability(): ?string
    {
        return $this->availability;
    }

    /**
     * Availability of the node.
     */
    public function setAvailability(?string $availability): self
    {
        $this->availability = $availability;

        return $this;
    }
}
