<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class ProgressDetail
{
    /**
     * @var int
     */
    protected $current;
    /**
     * @var int
     */
    protected $total;

    public function getCurrent(): ?int
    {
        return $this->current;
    }

    public function setCurrent(?int $current): self
    {
        $this->current = $current;

        return $this;
    }

    public function getTotal(): ?int
    {
        return $this->total;
    }

    public function setTotal(?int $total): self
    {
        $this->total = $total;

        return $this;
    }
}
