<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class SystemVersionComponentsItem
{
    /**
     * Name of the component.
     *
     * @var string
     */
    protected $name;
    /**
     * Version of the component.
     *
     * @var string
     */
    protected $version;
    /**
     * Key/value pairs of strings with additional information about the.
     *
     * @var mixed
     */
    protected $details;

    /**
     * Name of the component.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the component.
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Version of the component.
     */
    public function getVersion(): ?string
    {
        return $this->version;
    }

    /**
     * Version of the component.
     */
    public function setVersion(?string $version): self
    {
        $this->version = $version;

        return $this;
    }

    /**
     * Key/value pairs of strings with additional information about the.
     *
     * @return mixed
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Key/value pairs of strings with additional information about the.
     *
     * @param mixed $details
     */
    public function setDetails($details): self
    {
        $this->details = $details;

        return $this;
    }
}
