<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskSpecContainerSpecDNSConfig
{
    /**
     * The IP addresses of the name servers.
     *
     * @var string[]
     */
    protected $nameservers;
    /**
     * A search list for host-name lookup.
     *
     * @var string[]
     */
    protected $search;
    /**
     * A list of internal resolver variables to be modified (e.g.,.
     *
     * @var string[]
     */
    protected $options;

    /**
     * The IP addresses of the name servers.
     *
     * @return string[]|null
     */
    public function getNameservers(): ?array
    {
        return $this->nameservers;
    }

    /**
     * The IP addresses of the name servers.
     *
     * @param string[]|null $nameservers
     */
    public function setNameservers(?array $nameservers): self
    {
        $this->nameservers = $nameservers;

        return $this;
    }

    /**
     * A search list for host-name lookup.
     *
     * @return string[]|null
     */
    public function getSearch(): ?array
    {
        return $this->search;
    }

    /**
     * A search list for host-name lookup.
     *
     * @param string[]|null $search
     */
    public function setSearch(?array $search): self
    {
        $this->search = $search;

        return $this;
    }

    /**
     * A list of internal resolver variables to be modified (e.g.,.
     *
     * @return string[]|null
     */
    public function getOptions(): ?array
    {
        return $this->options;
    }

    /**
     * A list of internal resolver variables to be modified (e.g.,.
     *
     * @param string[]|null $options
     */
    public function setOptions(?array $options): self
    {
        $this->options = $options;

        return $this;
    }
}
