<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class TaskSpecContainerSpec
{
    /**
     * The image name to use for the container.
     *
     * @var string
     */
    protected $image;
    /**
     * User-defined key/value data.
     *
     * @var string[]
     */
    protected $labels;
    /**
     * The command to be run in the image.
     *
     * @var string[]
     */
    protected $command;
    /**
     * Arguments to the command.
     *
     * @var string[]
     */
    protected $args;
    /**
     * The hostname to use for the container, as a valid.
     *
     * @var string
     */
    protected $hostname;
    /**
     * A list of environment variables in the form `VAR=value`.
     *
     * @var string[]
     */
    protected $env;
    /**
     * The working directory for commands to run in.
     *
     * @var string
     */
    protected $dir;
    /**
     * The user inside the container.
     *
     * @var string
     */
    protected $user;
    /**
     * A list of additional groups that the container process will run as.
     *
     * @var string[]
     */
    protected $groups;
    /**
     * Security options for the container.
     *
     * @var TaskSpecContainerSpecPrivileges
     */
    protected $privileges;
    /**
     * Whether a pseudo-TTY should be allocated.
     *
     * @var bool
     */
    protected $tTY;
    /**
     * Open `stdin`.
     *
     * @var bool
     */
    protected $openStdin;
    /**
     * Mount the container's root filesystem as read only.
     *
     * @var bool
     */
    protected $readOnly;
    /**
     * Specification for mounts to be added to containers created as part.
     *
     * @var Mount[]
     */
    protected $mounts;
    /**
     * Signal to stop the container.
     *
     * @var string
     */
    protected $stopSignal;
    /**
     * Amount of time to wait for the container to terminate before.
     *
     * @var int
     */
    protected $stopGracePeriod;
    /**
     * A test to perform to check that the container is healthy.
     *
     * @var HealthConfig
     */
    protected $healthCheck;
    /**
     * A list of hostname/IP mappings to add to the container's `hosts`.
     *
     * @var string[]
     */
    protected $hosts;
    /**
     * Specification for DNS related configurations in resolver configuration.
     *
     * @var TaskSpecContainerSpecDNSConfig
     */
    protected $dNSConfig;
    /**
     * Secrets contains references to zero or more secrets that will be.
     *
     * @var TaskSpecContainerSpecSecretsItem[]
     */
    protected $secrets;
    /**
     * Configs contains references to zero or more configs that will be.
     *
     * @var TaskSpecContainerSpecConfigsItem[]
     */
    protected $configs;
    /**
     * Isolation technology of the containers running the service.
     *
     * @var string
     */
    protected $isolation;
    /**
     * Run an init inside the container that forwards signals and reaps.
     *
     * @var bool
     */
    protected $init;
    /**
     * Set kernel namedspaced parameters (sysctls) in the container.
     *
     * @var string[]
     */
    protected $sysctls;

    /**
     * The image name to use for the container.
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * The image name to use for the container.
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * User-defined key/value data.
     *
     * @return string[]|null
     */
    public function getLabels(): ?\ArrayObject
    {
        return $this->labels;
    }

    /**
     * User-defined key/value data.
     *
     * @param string[]|null $labels
     */
    public function setLabels(?\ArrayObject $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * The command to be run in the image.
     *
     * @return string[]|null
     */
    public function getCommand(): ?array
    {
        return $this->command;
    }

    /**
     * The command to be run in the image.
     *
     * @param string[]|null $command
     */
    public function setCommand(?array $command): self
    {
        $this->command = $command;

        return $this;
    }

    /**
     * Arguments to the command.
     *
     * @return string[]|null
     */
    public function getArgs(): ?array
    {
        return $this->args;
    }

    /**
     * Arguments to the command.
     *
     * @param string[]|null $args
     */
    public function setArgs(?array $args): self
    {
        $this->args = $args;

        return $this;
    }

    /**
     * The hostname to use for the container, as a valid.
     */
    public function getHostname(): ?string
    {
        return $this->hostname;
    }

    /**
     * The hostname to use for the container, as a valid.
     */
    public function setHostname(?string $hostname): self
    {
        $this->hostname = $hostname;

        return $this;
    }

    /**
     * A list of environment variables in the form `VAR=value`.
     *
     * @return string[]|null
     */
    public function getEnv(): ?array
    {
        return $this->env;
    }

    /**
     * A list of environment variables in the form `VAR=value`.
     *
     * @param string[]|null $env
     */
    public function setEnv(?array $env): self
    {
        $this->env = $env;

        return $this;
    }

    /**
     * The working directory for commands to run in.
     */
    public function getDir(): ?string
    {
        return $this->dir;
    }

    /**
     * The working directory for commands to run in.
     */
    public function setDir(?string $dir): self
    {
        $this->dir = $dir;

        return $this;
    }

    /**
     * The user inside the container.
     */
    public function getUser(): ?string
    {
        return $this->user;
    }

    /**
     * The user inside the container.
     */
    public function setUser(?string $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * A list of additional groups that the container process will run as.
     *
     * @return string[]|null
     */
    public function getGroups(): ?array
    {
        return $this->groups;
    }

    /**
     * A list of additional groups that the container process will run as.
     *
     * @param string[]|null $groups
     */
    public function setGroups(?array $groups): self
    {
        $this->groups = $groups;

        return $this;
    }

    /**
     * Security options for the container.
     */
    public function getPrivileges(): ?TaskSpecContainerSpecPrivileges
    {
        return $this->privileges;
    }

    /**
     * Security options for the container.
     */
    public function setPrivileges(?TaskSpecContainerSpecPrivileges $privileges): self
    {
        $this->privileges = $privileges;

        return $this;
    }

    /**
     * Whether a pseudo-TTY should be allocated.
     */
    public function getTTY(): ?bool
    {
        return $this->tTY;
    }

    /**
     * Whether a pseudo-TTY should be allocated.
     */
    public function setTTY(?bool $tTY): self
    {
        $this->tTY = $tTY;

        return $this;
    }

    /**
     * Open `stdin`.
     */
    public function getOpenStdin(): ?bool
    {
        return $this->openStdin;
    }

    /**
     * Open `stdin`.
     */
    public function setOpenStdin(?bool $openStdin): self
    {
        $this->openStdin = $openStdin;

        return $this;
    }

    /**
     * Mount the container's root filesystem as read only.
     */
    public function getReadOnly(): ?bool
    {
        return $this->readOnly;
    }

    /**
     * Mount the container's root filesystem as read only.
     */
    public function setReadOnly(?bool $readOnly): self
    {
        $this->readOnly = $readOnly;

        return $this;
    }

    /**
     * Specification for mounts to be added to containers created as part.
     *
     * @return Mount[]|null
     */
    public function getMounts(): ?array
    {
        return $this->mounts;
    }

    /**
     * Specification for mounts to be added to containers created as part.
     *
     * @param Mount[]|null $mounts
     */
    public function setMounts(?array $mounts): self
    {
        $this->mounts = $mounts;

        return $this;
    }

    /**
     * Signal to stop the container.
     */
    public function getStopSignal(): ?string
    {
        return $this->stopSignal;
    }

    /**
     * Signal to stop the container.
     */
    public function setStopSignal(?string $stopSignal): self
    {
        $this->stopSignal = $stopSignal;

        return $this;
    }

    /**
     * Amount of time to wait for the container to terminate before.
     */
    public function getStopGracePeriod(): ?int
    {
        return $this->stopGracePeriod;
    }

    /**
     * Amount of time to wait for the container to terminate before.
     */
    public function setStopGracePeriod(?int $stopGracePeriod): self
    {
        $this->stopGracePeriod = $stopGracePeriod;

        return $this;
    }

    /**
     * A test to perform to check that the container is healthy.
     */
    public function getHealthCheck(): ?HealthConfig
    {
        return $this->healthCheck;
    }

    /**
     * A test to perform to check that the container is healthy.
     */
    public function setHealthCheck(?HealthConfig $healthCheck): self
    {
        $this->healthCheck = $healthCheck;

        return $this;
    }

    /**
     * A list of hostname/IP mappings to add to the container's `hosts`.
     *
     * @return string[]|null
     */
    public function getHosts(): ?array
    {
        return $this->hosts;
    }

    /**
     * A list of hostname/IP mappings to add to the container's `hosts`.
     *
     * @param string[]|null $hosts
     */
    public function setHosts(?array $hosts): self
    {
        $this->hosts = $hosts;

        return $this;
    }

    /**
     * Specification for DNS related configurations in resolver configuration.
     */
    public function getDNSConfig(): ?TaskSpecContainerSpecDNSConfig
    {
        return $this->dNSConfig;
    }

    /**
     * Specification for DNS related configurations in resolver configuration.
     */
    public function setDNSConfig(?TaskSpecContainerSpecDNSConfig $dNSConfig): self
    {
        $this->dNSConfig = $dNSConfig;

        return $this;
    }

    /**
     * Secrets contains references to zero or more secrets that will be.
     *
     * @return TaskSpecContainerSpecSecretsItem[]|null
     */
    public function getSecrets(): ?array
    {
        return $this->secrets;
    }

    /**
     * Secrets contains references to zero or more secrets that will be.
     *
     * @param TaskSpecContainerSpecSecretsItem[]|null $secrets
     */
    public function setSecrets(?array $secrets): self
    {
        $this->secrets = $secrets;

        return $this;
    }

    /**
     * Configs contains references to zero or more configs that will be.
     *
     * @return TaskSpecContainerSpecConfigsItem[]|null
     */
    public function getConfigs(): ?array
    {
        return $this->configs;
    }

    /**
     * Configs contains references to zero or more configs that will be.
     *
     * @param TaskSpecContainerSpecConfigsItem[]|null $configs
     */
    public function setConfigs(?array $configs): self
    {
        $this->configs = $configs;

        return $this;
    }

    /**
     * Isolation technology of the containers running the service.
     */
    public function getIsolation(): ?string
    {
        return $this->isolation;
    }

    /**
     * Isolation technology of the containers running the service.
     */
    public function setIsolation(?string $isolation): self
    {
        $this->isolation = $isolation;

        return $this;
    }

    /**
     * Run an init inside the container that forwards signals and reaps.
     */
    public function getInit(): ?bool
    {
        return $this->init;
    }

    /**
     * Run an init inside the container that forwards signals and reaps.
     */
    public function setInit(?bool $init): self
    {
        $this->init = $init;

        return $this;
    }

    /**
     * Set kernel namedspaced parameters (sysctls) in the container.
     *
     * @return string[]|null
     */
    public function getSysctls(): ?\ArrayObject
    {
        return $this->sysctls;
    }

    /**
     * Set kernel namedspaced parameters (sysctls) in the container.
     *
     * @param string[]|null $sysctls
     */
    public function setSysctls(?\ArrayObject $sysctls): self
    {
        $this->sysctls = $sysctls;

        return $this;
    }
}
