<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class Volume
{
    /**
     * Name of the volume.
     *
     * @var string
     */
    protected $name;
    /**
     * Name of the volume driver used by the volume.
     *
     * @var string
     */
    protected $driver;
    /**
     * Mount path of the volume on the host.
     *
     * @var string
     */
    protected $mountpoint;
    /**
     * Date/Time the volume was created.
     *
     * @var string
     */
    protected $createdAt;
    /**
     * Low-level details about the volume, provided by the volume driver.
     *
     * @var mixed[]
     */
    protected $status;
    /**
     * User-defined key/value metadata.
     *
     * @var string[]
     */
    protected $labels;
    /**
     * The level at which the volume exists. Either `global` for cluster-wide,.
     *
     * @var string
     */
    protected $scope = 'local';
    /**
     * The driver specific options used when creating the volume.
     *
     * @var string[]
     */
    protected $options;
    /**
     * Usage details about the volume. This information is used by the.
     *
     * @var VolumeUsageData
     */
    protected $usageData;

    /**
     * Name of the volume.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Name of the volume.
     */
    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Name of the volume driver used by the volume.
     */
    public function getDriver(): ?string
    {
        return $this->driver;
    }

    /**
     * Name of the volume driver used by the volume.
     */
    public function setDriver(?string $driver): self
    {
        $this->driver = $driver;

        return $this;
    }

    /**
     * Mount path of the volume on the host.
     */
    public function getMountpoint(): ?string
    {
        return $this->mountpoint;
    }

    /**
     * Mount path of the volume on the host.
     */
    public function setMountpoint(?string $mountpoint): self
    {
        $this->mountpoint = $mountpoint;

        return $this;
    }

    /**
     * Date/Time the volume was created.
     */
    public function getCreatedAt(): ?string
    {
        return $this->createdAt;
    }

    /**
     * Date/Time the volume was created.
     */
    public function setCreatedAt(?string $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Low-level details about the volume, provided by the volume driver.
     *
     * @return mixed[]|null
     */
    public function getStatus(): ?\ArrayObject
    {
        return $this->status;
    }

    /**
     * Low-level details about the volume, provided by the volume driver.
     *
     * @param mixed[]|null $status
     */
    public function setStatus(?\ArrayObject $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * User-defined key/value metadata.
     *
     * @return string[]|null
     */
    public function getLabels(): ?\ArrayObject
    {
        return $this->labels;
    }

    /**
     * User-defined key/value metadata.
     *
     * @param string[]|null $labels
     */
    public function setLabels(?\ArrayObject $labels): self
    {
        $this->labels = $labels;

        return $this;
    }

    /**
     * The level at which the volume exists. Either `global` for cluster-wide,.
     */
    public function getScope(): ?string
    {
        return $this->scope;
    }

    /**
     * The level at which the volume exists. Either `global` for cluster-wide,.
     */
    public function setScope(?string $scope): self
    {
        $this->scope = $scope;

        return $this;
    }

    /**
     * The driver specific options used when creating the volume.
     *
     * @return string[]|null
     */
    public function getOptions(): ?\ArrayObject
    {
        return $this->options;
    }

    /**
     * The driver specific options used when creating the volume.
     *
     * @param string[]|null $options
     */
    public function setOptions(?\ArrayObject $options): self
    {
        $this->options = $options;

        return $this;
    }

    /**
     * Usage details about the volume. This information is used by the.
     */
    public function getUsageData(): ?VolumeUsageData
    {
        return $this->usageData;
    }

    /**
     * Usage details about the volume. This information is used by the.
     */
    public function setUsageData(?VolumeUsageData $usageData): self
    {
        $this->usageData = $usageData;

        return $this;
    }
}
