<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace Docker\API\Model;

class VolumeUsageData
{
    /**
     * Amount of disk space used by the volume (in bytes). This information.
     *
     * @var int
     */
    protected $size = -1;
    /**
     * The number of containers referencing this volume. This field.
     *
     * @var int
     */
    protected $refCount = -1;

    /**
     * Amount of disk space used by the volume (in bytes). This information.
     */
    public function getSize(): ?int
    {
        return $this->size;
    }

    /**
     * Amount of disk space used by the volume (in bytes). This information.
     */
    public function setSize(?int $size): self
    {
        $this->size = $size;

        return $this;
    }

    /**
     * The number of containers referencing this volume. This field.
     */
    public function getRefCount(): ?int
    {
        return $this->refCount;
    }

    /**
     * The number of containers referencing this volume. This field.
     */
    public function setRefCount(?int $refCount): self
    {
        $this->refCount = $refCount;

        return $this;
    }
}
